@startuml HU01_clases
class Cliente {
  - idCliente: int
  - nombre: String
  - telefono: String
  - correo: String
  - contrasenaHash: String
  - fechaRegistro: Date
  + registrarCuenta(): boolean
  + validarCorreo(): boolean
}

class ControladorCuenta {
  + enviarRegistro(nombre: String, telefono: String, correo: String): void
  + validarCampos(): boolean
  + validarFormatoCorreo(correo: String): boolean
}

class RepositorioCliente {
  + buscarPorCorreo(correo: String): Cliente
  + guardar(cliente: Cliente): boolean
}

ControladorCuenta "1" --> "0..1" Cliente : crea >
ControladorCuenta "1" --> "1" RepositorioCliente : usa >
RepositorioCliente "1" --> "*" Cliente : administra >
@enduml
