@startuml HU02_casos_uso
left to right direction
actor Administrador

rectangle "Sistema BarberLosPeluchitos" {
  usecase "Registrar barbero" as UC1
  usecase "Cargar horarios de disponibilidad" as UC2
  usecase "Editar disponibilidad" as UC3
  usecase "Mostrar error: rango de horario invalido" as UC4
}

Administrador --> UC1
Administrador --> UC3
UC1 .> UC2 : <<include>>
UC4 .> UC2 : <<extend>>
@enduml
